### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by sbruder** [fablab-nea/doku#1]
Welche Lizent wollen wir denn hierfür verwenden?
CC-BY-SA? Oder GPLv3+? Oder ganz andere?

**Comment by mirabilos** [comment]
/*-
     * Copyright © year, year, year, …
     *      First M. Last <user@host.domain>
     *
     * Provided that these terms and disclaimer and all copyright notices
     * are retained or reproduced in an accompanying document, permission
     * is granted to deal in this work without restriction, including un‐
     * limited rights to use, publicly perform, distribute, sell, modify,
     * merge, give away, or sublicence.
     *
     * This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
     * the utmost extent permitted by applicable law, neither express nor
     * implied; without malicious intent or gross negligence. In no event
     * may a licensor, author or contributor be held liable for indirect,
     * direct, other damage, loss, or other issues arising in any way out
     * of dealing in the work, even if advised of the possibility of such
     * damage or existence of a defect, except proven that it results out
     * of said person’s immediate fault when using the work as intended.
     */

**Comment by sbruder** [comment]
Hallo mirabilos,

ja, die MirOS-Lizenz kenne ich, nur ob dir für jeden akzeptabel ist, weiß ich nicht, da müssten wir mal eine Umfrage unter Mitgliedern durchführen.

Trotzdem danke!

**Comment by mirabilos** [comment]
Simon Bruder dixit:

>Hallo mirabilos,
>
>ja, die MirOS-Lizenz kenne ich, nur ob dir für jeden akzeptabel ist,
>weiß ich nicht, da müssten wir mal eine Umfrage unter Mitgliedern
>durchführen.

Jo, das war nur der Vorschlag, dies zu tun.

>Trotzdem danke!

Gern!

Gruß
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt

**Comment by sbruder** [comment]
closed b716235
